main: me.SuperRonanCraft.BetterRTPAddons.Main
version: ${project.version}
api-version: '1.13'
folia-supported: true
name: BetterRTPAddons
depend: [BetterRTP]
softdepend: [ProtocolLib]

permissions:
  betterrtp.addon.portals:
    description: Ability to use the portals addon commands

